### ISSUE TITLE
Error communicating with Postgres database error="pq: role \"mattrax_db\" does not exist"

### ISSUE THREAD

**Issue by hxvxt2** [mattrax/Mattrax#1]
Hi,

I am trying to run on my local machine but running into an issue.
**Terminal 1:**
`docker-compose -f ./docker-compose-dev.yml up`
Run fine but postgres runs on default port even when I changed the ports to 5435 in my `docker-compose-dev.yml`

**Terminal 2:**
`go run ./cmd/mattrax --db "postgres://mattrax_db:password@localhost/mattrax?sslmode=disable" --domain mdm.example.com  --debug`

Fails with below error:
```
7:51PM FTL Error communicating with Postgres database error="pq: role \"mattrax_db\" does not exist"
exit status 1
```

**Here is my docker-compose-dev.yml**
```
version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mattrax_db
      POSTGRES_ROLE: mattrax_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mattraxs
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
      - type: bind
        source: ./sql/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        read_only: true
    command:
      - "postgres"
      - "-c"
      - "mattrax.upn = NULL"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
  # zipkin:
  #   image: openzipkin/zipkin-slim
  #   ports:
  #     - 127.0.0.1:9411:9411

volumes:
  database-data: {}

```
What am i missing?

Thanks
